- id: must-annotate
  name: must-annotate
  description: Enforce type annotation presence in Python code
  entry: must-annotate check --fail-on-error
  language: python
  types: [python]
  pass_filenames: true
